name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3

      - name: ASDF Setup
        uses: asdf-vm/actions/setup@v1

      - name: ASDF Cache
        id: asdf-cache
        uses: actions/cache@v3
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Install CD tools from .tool-versions
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test
